name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [client, server]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: |
          cd ${{ matrix.dir }}
          npm ci

      - name: Run ESLint
        run: |
          cd ${{ matrix.dir }}
          npx eslint .

      - name: Check Prettier
        run: |
          cd ${{ matrix.dir }}
          npx prettier --check .
